object AppRoutes {
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val HOME = "home"
    const val MY_POSTS = "my_posts"
    const val PUBLISH = "publish"
    const val MESSAGE = "message"
    const val CHAT_ROOM = "chat_room/{sessionId}/{targetName}/{targetType}"
    const val SUBSCRIBE_SETTING = "subscribe_setting"
    const val PROFILE = "profile"
    const val PROFILE_EDIT = "profile_edit"
    const val COMPANY_BINDING = "company_binding"
    const val VERIFICATION = "verification"
    const val COMPANY_REGISTER = "company_register"
    const val POST_DETAIL = "post_detail/{postId}"
    const val POST_EDIT = "post_edit/{postId}"
    const val COMPANY_DETAIL = "company_detail/{companyId}"
    const val PERSON_DETAIL = "person_detail/{personId}"
    const val MESSAGE_LIST = "message_list"
    const val MY_FAVORITES = "my_favorites"
    const val TAIL_LIST = "tail_list"
} 